import 'package:basketball/domain/entities/game.dart';
import 'package:basketball/domain/entities/period_points.dart';
import 'package:basketball/domain/entities/player.dart';
import 'package:basketball/domain/entities/point.dart';
import 'package:basketball/domain/entities/team.dart';
import 'package:basketball/resources/resources.dart';

final mockGame = Game(
  place: 'ТМ. 2 зал',
  dateTime: DateTime(
    2023,
    2,
    5,
    15,
    30,
  ),
  leftTeam: Team(
    name: 'What\'s Up',
    imagePath: TeamLogos.trud,
    points: const PeriodPoints(
      first: 16,
      second: 13,
      third: 14,
      fourth: 17,
    ),
    players: mockPlayers,
    minutes: DateTime(
      2022,
      1,
      1,
      0,
      22,
      12,
    ),
    totalPoints: 60,
    twoPoints: const TotalDone(done: 3, total: 3),
    threePoints: const TotalDone(done: 2, total: 3),
    penalty: const TotalDone(done: 3, total: 3),
    ssh: 0,
    chsh: 0,
    pb: 0,
    gp: 1,
    ph: 2,
    bsh: 3,
    pt: 0,
    f: 0,
    fs: 0,
    plusMinus: -5,
    kpi: 0,
  ),
  rightTeam: Team(
    name: 'TeamTeam (2)',
    imagePath: TeamLogos.mba,
    points: const PeriodPoints(
      first: 11,
      second: 15,
      third: 10,
      fourth: 20,
    ),
    players: mockPlayers.reversed.toList(),
    minutes: DateTime(
      2022,
      1,
      1,
      0,
      20,
      32,
    ),
    totalPoints: 56,
    twoPoints: const TotalDone(done: 3, total: 3),
    threePoints: const TotalDone(done: 2, total: 3),
    penalty: const TotalDone(done: 3, total: 3),
    ssh: 0,
    chsh: 0,
    pb: 0,
    gp: 1,
    ph: 2,
    bsh: 3,
    pt: 0,
    f: 0,
    fs: 0,
    plusMinus: -5,
    kpi: 0,
  ),
);

final mockPlayers = [
  Player(
    imagePath: 'https://cdn.nba.com/headshots/nba/latest/260x190/1628389.png',
    number: 12,
    surname: 'Клыков',
    name: 'Михаил',
    minutes: DateTime(
      2022,
      1,
      1,
      0,
      10,
      54,
    ),
    totalPoints: 6,
    twoPoints: const TotalDone(done: 3, total: 3),
    threePoints: const TotalDone(done: 2, total: 3),
    penalty: const TotalDone(done: 3, total: 3),
    ssh: 0,
    chsh: 0,
    pb: 0,
    gp: 1,
    ph: 2,
    bsh: 3,
    pt: 0,
    f: 0,
    fs: 0,
    plusMinus: -5,
    kpi: 0,
  ),
  Player(
    imagePath: 'https://cdn.nba.com/headshots/nba/latest/260x190/203500.png',
    number: 22,
    surname: 'Беззубов',
    name: 'Николай',
    minutes: DateTime(
      2022,
      1,
      1,
      0,
      5,
      3,
    ),
    totalPoints: 9,
    twoPoints: const TotalDone(done: 1, total: 1),
    threePoints: const TotalDone(done: 3, total: 8),
    penalty: const TotalDone(done: 3, total: 3),
    ssh: 0,
    chsh: 0,
    pb: 0,
    gp: 1,
    ph: 2,
    bsh: 3,
    pt: 0,
    f: 0,
    fs: 0,
    plusMinus: -5,
    kpi: 0,
  ),
  Player(
    imagePath: 'https://cdn.nba.com/headshots/nba/latest/260x190/1630173.png',
    number: 30,
    surname: 'Голобородько',
    name: 'Дмитрий',
    minutes: DateTime(
      2022,
      1,
      1,
      0,
      22,
      30,
    ),
    totalPoints: 0,
    twoPoints: const TotalDone(done: 6, total: 7),
    threePoints: const TotalDone(done: 1, total: 2),
    penalty: const TotalDone(done: 3, total: 3),
    ssh: 0,
    chsh: 0,
    pb: 0,
    gp: 1,
    ph: 2,
    bsh: 3,
    pt: 0,
    f: 0,
    fs: 0,
    plusMinus: -5,
    kpi: 0,
  ),
  Player(
    imagePath: 'https://cdn.nba.com/headshots/nba/latest/260x190/1630534.png',
    number: 14,
    surname: 'Горин',
    name: 'Никита',
    minutes: DateTime(
      2022,
      1,
      1,
      0,
      29,
      22,
    ),
    totalPoints: 2,
    twoPoints: const TotalDone(done: 0, total: 3),
    threePoints: const TotalDone(done: 14, total: 14),
    penalty: const TotalDone(done: 3, total: 3),
    ssh: 0,
    chsh: 0,
    pb: 0,
    gp: 1,
    ph: 2,
    bsh: 3,
    pt: 0,
    f: 0,
    fs: 0,
    plusMinus: -5,
    kpi: 0,
  ),
  Player(
    imagePath: 'https://cdn.nba.com/headshots/nba/latest/260x190/1630583.png',
    number: 25,
    surname: 'Маликов',
    name: 'Евгений',
    minutes: DateTime(
      2022,
      1,
      1,
      0,
      40,
      17,
    ),
    totalPoints: 8,
    twoPoints: const TotalDone(done: 1, total: 3),
    threePoints: const TotalDone(done: 3, total: 9),
    penalty: const TotalDone(done: 3, total: 3),
    ssh: 0,
    chsh: 0,
    pb: 0,
    gp: 1,
    ph: 2,
    bsh: 3,
    pt: 0,
    f: 0,
    fs: 0,
    plusMinus: -5,
    kpi: 0,
  ),
  Player(
    imagePath: 'https://cdn.nba.com/headshots/nba/latest/260x190/1629638.png',
    number: 17,
    surname: 'Русаков',
    name: 'Шамиль',
    minutes: DateTime(
      2022,
      1,
      1,
      0,
      10,
      32,
    ),
    totalPoints: 8,
    twoPoints: const TotalDone(done: 2, total: 3),
    threePoints: const TotalDone(done: 3, total: 9),
    penalty: const TotalDone(done: 3, total: 3),
    ssh: 0,
    chsh: 0,
    pb: 0,
    gp: 1,
    ph: 2,
    bsh: 3,
    pt: 0,
    f: 0,
    fs: 0,
    plusMinus: -5,
    kpi: 0,
  ),
  Player(
    imagePath: 'https://cdn.nba.com/headshots/nba/latest/260x190/1628960.png',
    number: 11,
    surname: 'Лыськов',
    name: 'Георгий',
    minutes: DateTime(
      2022,
      1,
      1,
      0,
      19,
      19,
    ),
    totalPoints: 8,
    twoPoints: const TotalDone(done: 2, total: 3),
    threePoints: const TotalDone(done: 3, total: 9),
    penalty: const TotalDone(done: 3, total: 3),
    ssh: 0,
    chsh: 0,
    pb: 0,
    gp: 1,
    ph: 2,
    bsh: 3,
    pt: 0,
    f: 0,
    fs: 0,
    plusMinus: -5,
    kpi: 0,
  ),
  Player(
    imagePath: 'https://cdn.nba.com/headshots/nba/latest/260x190/203507.png',
    number: 29,
    surname: 'Павлов',
    name: 'Геннадий',
    minutes: DateTime(
      2022,
      1,
      1,
      0,
      10,
      15,
    ),
    totalPoints: 8,
    twoPoints: const TotalDone(done: 2, total: 3),
    threePoints: const TotalDone(done: 3, total: 9),
    penalty: const TotalDone(done: 3, total: 3),
    ssh: 0,
    chsh: 0,
    pb: 0,
    gp: 1,
    ph: 2,
    bsh: 3,
    pt: 0,
    f: 0,
    fs: 0,
    plusMinus: -5,
    kpi: 0,
  ),
  Player(
    imagePath: 'https://cdn.nba.com/headshots/nba/latest/260x190/1630163.png',
    number: 29,
    surname: 'Шилин',
    name: 'Кирилл',
    minutes: DateTime(
      2022,
      1,
      1,
      0,
      10,
      15,
    ),
    totalPoints: 8,
    twoPoints: const TotalDone(done: 2, total: 3),
    threePoints: const TotalDone(done: 3, total: 9),
    penalty: const TotalDone(done: 3, total: 3),
    ssh: 0,
    chsh: 0,
    pb: 0,
    gp: 1,
    ph: 2,
    bsh: 3,
    pt: 0,
    f: 0,
    fs: 0,
    plusMinus: -5,
    kpi: 0,
  ),
  Player(
    imagePath: 'https://cdn.nba.com/headshots/nba/latest/260x190/1628962.png',
    number: 29,
    surname: 'Витаньев',
    name: 'Владимир',
    minutes: DateTime(
      2022,
      1,
      1,
      0,
      10,
      15,
    ),
    totalPoints: 8,
    twoPoints: const TotalDone(done: 2, total: 3),
    threePoints: const TotalDone(done: 3, total: 9),
    penalty: const TotalDone(done: 3, total: 3),
    ssh: 0,
    chsh: 0,
    pb: 0,
    gp: 1,
    ph: 2,
    bsh: 3,
    pt: 0,
    f: 0,
    fs: 0,
    plusMinus: -5,
    kpi: 0,
  ),
  Player(
    imagePath: 'https://cdn.nba.com/headshots/nba/latest/260x190/1630641.png',
    number: 29,
    surname: 'Павлов',
    name: 'Геннадий',
    minutes: DateTime(
      2022,
      1,
      1,
      0,
      10,
      15,
    ),
    totalPoints: 8,
    twoPoints: const TotalDone(done: 2, total: 3),
    threePoints: const TotalDone(done: 3, total: 9),
    penalty: const TotalDone(done: 3, total: 3),
    ssh: 0,
    chsh: 0,
    pb: 0,
    gp: 1,
    ph: 2,
    bsh: 3,
    pt: 0,
    f: 0,
    fs: 0,
    plusMinus: -5,
    kpi: 0,
  ),
];
